In [1]:
import pandas as pd
qid_query = pd.read_csv("qid_query.tsv", sep="\t", names=["qid", "query"])
qid_url_rating = pd.read_csv("qid_url_rating.tsv", sep="\t", names=["qid", "url", "rating"])
hostid_url = pd.read_csv("hostid_url.tsv", sep="\t", names=["hostid", "url"])

In [2]:
qid_query.head()

      qid                                              query
0   10387          batman arkham city будет русский перевод?
1  107538           Список белорусской литературы по лизингу
2  150126                                   написание review
3  168170                         медаль в подарок на 30 лет
4  176370  что означает рожь и пшеница годом родится а ве...

In [3]:
qid_url_rating.head()

     qid                                                url  rating
0  10387                       http://batman-arkhamcity.ru/    0.00
1  10387  http://bigtorrents.org/publ/batman_arkham_city...    0.14
2  10387  http://consolelife.ru/xbox-360/6577-o-rossiysk...    0.14
3  10387  http://dic.academic.ru/book.nsf/3662736/Batman...    0.00
4  10387      http://forum.csmania.ru/viewtopic.php?t=25986    0.14

In [4]:
hostid_url.head()

   hostid                                                url
0     100                                  http://cons66.ru/
1    1000        http://www.pozdravleniya.biz/stihi/detskie/
2    1001  http://www.pravda.ru/society/family/pbringing/...
3    1002        http://www.pravpiter.ru/gorn/n015/ta003.htm
4    1003  http://www.pregnancycalendar.ru/biblioteka/vse...

In [8]:
qid_url_rating_hostid = pd.merge(qid_url_rating, hostid_url, on='url')
qid_url_rating_hostid.sort_values(by='qid')

        qid                                                url  rating  hostid
0     10387                       http://batman-arkhamcity.ru/    0.00      64
28    10387  http://www.batmanforever.ru/batman-news/709-ru...    0.14     696
29    10387        http://www.comicsdb.ru/publishers/10/40090/    0.14     740
30    10387  http://www.comicsdb.ru/publishers/10/40090/com...    0.00     740
31    10387  http://www.comicsdb.ru/publishers/10/40090/com...    0.00     740
..      ...                                                ...     ...     ...
828  380923     http://mathematik.com.ua/queue/full_queue.aspx    0.00     326
829  380923        http://matmir.narod.ru/MO_Geometruya_8.html    0.00     327
830  380923  http://nsportal.ru/shkola/geometriya/library/d...    0.00     386
821  380923            http://gdz-top.ru/?one=1&two=3&three=26    0.14     179
853  380923              http://xn--80ashg.xn--p1ai/pdf/56.pdf    0.07    1172

[854 rows x 4 columns]

In [9]:
qid_url_rating_hostid.sort_values(by='qid').head(10)

      qid                                                url  rating  hostid
0   10387                       http://batman-arkhamcity.ru/    0.00      64
28  10387  http://www.batmanforever.ru/batman-news/709-ru...    0.14     696
29  10387        http://www.comicsdb.ru/publishers/10/40090/    0.14     740
30  10387  http://www.comicsdb.ru/publishers/10/40090/com...    0.00     740
31  10387  http://www.comicsdb.ru/publishers/10/40090/com...    0.00     740
32  10387  http://www.gamer.ru/batman-arkham-city/batman-...    0.00     812
33  10387  http://www.gamer.ru/batman-arkham-city/batman-...    0.00     812
34  10387  http://www.gamer.ru/batman-arkham-city/v-batma...    0.00     812
35  10387  http://www.games-tv.ru/treilers/batman_arkham_...    0.00     814
36  10387  http://www.games-tv.ru/treilers/batman_arkham_...    0.00     814

In [10]:
qid_url_rating_hostid.sort_values(by='qid').tail(7)

        qid                                                url  rating  hostid
826  380923                http://livetheme.ru/9-klass/page/2/    0.00     300
827  380923  http://matematikayamal.ucoz.ru/load/6_klass/ko...    0.00     325
828  380923     http://mathematik.com.ua/queue/full_queue.aspx    0.00     326
829  380923        http://matmir.narod.ru/MO_Geometruya_8.html    0.00     327
830  380923  http://nsportal.ru/shkola/geometriya/library/d...    0.00     386
821  380923            http://gdz-top.ru/?one=1&two=3&three=26    0.14     179
853  380923              http://xn--80ashg.xn--p1ai/pdf/56.pdf    0.07    1172

In [11]:
qid_url_rating_hostid.sort_values(by='qid').head(20).tail(10)

      qid                                                url  rating  hostid
37  10387  http://www.games-tv.ru/treilers/batman_arkham_...    0.07     814
38  10387         http://www.igromania.ru/videomania/148196/    0.00     846
40  10387  http://www.jurnalu.ru/online-reading/comicsonl...    0.14     871
41  10387  http://www.microsofttranslator.com/bv.aspx?ref...    0.00     922
42  10387  http://www.playground.ru/blogs/batman_arkham_c...    0.07     995
43  10387  http://www.playground.ru/blogs/batman_arkham_c...    0.14     995
44  10387  http://www.playground.ru/blogs/batman_arkham_c...    0.07     995
45  10387  http://www.playground.ru/blogs/batman_arkham_c...    0.00     995
46  10387  http://www.rutor.org/torrent/155539/batman-ark...    0.00    1042
47  10387  http://www.rutor.org/torrent/196061/batman-ark...    0.00    1042

In [32]:
print(qid_url_rating_hostid['qid'].max())
print(qid_url_rating_hostid['qid'].min())
print(qid_url_rating_hostid['qid'].mean())

380923
10387
198648.79508196723

In [35]:
len(qid_url_rating_hostid[qid_url_rating_hostid.qid == 347852])

31

In [38]:
qid_url_rating_hostid[qid_url_rating_hostid.qid == 347852].sort_values(by='rating', ascending=False).head(10)

        qid                                                url  rating  hostid
652  347852                               http://uralsoft.net/    0.41     590
655  347852                                http://uralsoft.ru/    0.14     591
654  347852                       http://uralsoft.net/?paged=3    0.14     590
653  347852                       http://uralsoft.net/?paged=2    0.14     590
651  347852                                    http://ur66.ru/    0.14     589
657  347852                              http://uraltrack.net/    0.14     593
656  347852                          http://uralsoft.ucoz.net/    0.07     592
650  347852  http://torrent-windows.net/windows/windows_8/1...    0.07     556
648  347852  http://torrent-windows.net/windows/windows_8/1...    0.07     556
658  347852      http://www.cmsmagazine.ru/creators/ural-soft/    0.07     736

examples of recommendation systems:


1) Search engine, for example google  
User query is 'how to play chess'  
item to recommend are 'wikipedia.org', 'chesskid.com' , 'chesscoachonline.com', youtube videos   
I think the biggest relevance has wikipedia, beacuse it is the most popular site with information which is always useful, other sites has not so big relevance. I think relevance depends on site name(if some words of query are in the site name, then  this site can be useful) and the count of coincidental word in the query and in the site is too important

2) Spotify
User query is 'pop music'  
items to recommend are playlist 'pop music 2020', album 'top 10 pop music', singers with genre 'pop'   
I think the most relevance have playlists, named 'pop music' beacuse the name is equals to query

3) Netflix
user query is 'horror'  
items to recommend are films 'It', 'Pet Sematary', 'The Ring'  
I think the relevance of films are about the same.  
I think relevance depends on genre of movies, the director of movie, the people responses.